const testData = {
  tasks: [
    {
      id: "1",
      bill: "263299491.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-18",
      isCertified: true,
      lga: "Egbe-Idimu",
      occupation: "Civil engineers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Lorem Ipsom",
      timeBlock: "Day",
      yearsOfExp: "7-9 years",
      status: "created",
      principal: "001",
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      id: "2",
      bill: "462944160.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-25",
      isCertified: true,
      lga: "Eti-Osa East",
      occupation: "Architects and town planners",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-10",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Fetch Car",
      timeBlock: "Night",
      yearsOfExp: "4-6 years",
      status: "created",
      principal: "001",
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      id: "3",
      bill: "92588832.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-17",
      isCertified: false,
      lga: "Lagos Mainland",
      occupation: "Medical doctors",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-08",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Healing",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      status: "created",
      principal: "001",
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      id: "4",
      bill: "925888320.00",
      eduLevel: "PhD",
      endDate: "2023-03-24",
      isCertified: true,
      lga: "Apapa",
      occupation: "Biologists, zoologists and related scientists",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-06",
      state: "Lagos",
      timeBlock: "Night",
      yearsOfExp: "10 years & above",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Sciency stuff",
      status: "approved",
      principal: "001",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
    },
    {
      id: "5",
      bill: "263299491.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-18",
      isCertified: true,
      lga: "Egbe-Idimu",
      occupation: "Civil engineers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Build Bridge",
      timeBlock: "Day",
      yearsOfExp: "7-9 years",
      status: "approved",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
    },
    {
      id: "6",
      bill: "462944160.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-25",
      isCertified: true,
      lga: "Eti-Osa East",
      occupation: "Architects and town planners",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-10",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Design building",
      timeBlock: "Night",
      yearsOfExp: "4-6 years",
      status: "approved",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
    },
    {
      id: "7",
      bill: "92588832.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-17",
      isCertified: false,
      lga: "Lagos Mainland",
      occupation: "Medical doctors",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-08",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "No Ga Furueru",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      status: "assigned",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      principal: "001",
      paymentId: "001",
      proxzi: "002",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
    },
    {
      id: "8",
      bill: "925888320.00",
      eduLevel: "PhD",
      endDate: "2023-03-24",
      isCertified: true,
      lga: "Apapa",
      occupation: "Biologists, zoologists and related scientists",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-06",
      state: "Lagos",
      timeBlock: "Night",
      yearsOfExp: "10 years & above",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Treat my pokemon",
      status: "assigned",
      offers: [{ id: "002" }],
      principal: "003",
      paymentId: "002",
      proxzi: "002",
      createdAt: "2023-02-22T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
    },
    {
      id: "9",
      bill: "34720812.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-07",
      isCertified: true,
      lga: "Amuwo-Odofin",
      occupation: "Lawyers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Somebody save me",
      status: "assigned",
      offers: [{ id: "006" }],
      principal: "001",
      paymentId: "003",
      proxzi: "006",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
    },
    {
      id: "10",
      bill: "925888320.00",
      eduLevel: "PhD",
      endDate: "2023-03-24",
      isCertified: true,
      lga: "Apapa",
      occupation: "Biologists, zoologists and related scientists",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-06",
      state: "Lagos",
      timeBlock: "Night",
      yearsOfExp: "10 years & above",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Dinosaur resurrection",
      status: "assigned",
      offers: [{ id: "002" }],
      principal: "001",
      paymentId: "004",
      proxzi: "002",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
    },
    {
      id: "11",
      bill: "263299491.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-18",
      isCertified: true,
      lga: "Egbe-Idimu",
      occupation: "Civil engineers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Build Palace",
      timeBlock: "Day",
      yearsOfExp: "7-9 years",
      status: "assigned",
      offers: [{ id: "002" }, { id: "004" }],
      principal: "001",
      paymentId: "005",
      proxzi: "004",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
    },
    {
      id: "12",
      bill: "462944160.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-25",
      isCertified: true,
      lga: "Eti-Osa East",
      occupation: "Architects and town planners",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-10",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Plan base",
      timeBlock: "Night",
      yearsOfExp: "4-6 years",
      status: "assigned",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      principal: "001",
      paymentId: "006",
      proxzi: "002",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
    },
    {
      id: "13",
      bill: "92588832.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-17",
      isCertified: false,
      lga: "Lagos Mainland",
      occupation: "Medical doctors",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-08",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Sword in my chest",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      status: "started",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      proxzi: "002",
      paymentId: "007",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
    },
    {
      id: "14",
      bill: "925888320.00",
      eduLevel: "PhD",
      endDate: "2023-03-24",
      isCertified: true,
      lga: "Apapa",
      occupation: "Biologists, zoologists and related scientists",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-06",
      state: "Lagos",
      timeBlock: "Night",
      yearsOfExp: "10 years & above",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Whale research",
      status: "started",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }],
      proxzi: "004",
      paymentId: "008",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
    },
    {
      id: "15",
      bill: "34720812.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-07",
      isCertified: true,
      lga: "Amuwo-Odofin",
      occupation: "Lawyers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Divorce case",
      status: "started",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      proxzi: "006",
      paymentId: "009",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
    },
    {
      id: "16",
      bill: "92588832.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-17",
      isCertified: false,
      lga: "Lagos Mainland",
      occupation: "Medical doctors",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-08",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Heal the world",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      status: "completed",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      proxzi: "002",
      paymentId: "010",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
      completedAt: "2023-02-26T03:57:50.232+00:00",
    },
    {
      id: "17",
      bill: "925888320.00",
      eduLevel: "PhD",
      endDate: "2023-03-24",
      isCertified: true,
      lga: "Apapa",
      occupation: "Biologists, zoologists and related scientists",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-06",
      state: "Lagos",
      timeBlock: "Night",
      yearsOfExp: "10 years & above",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Panda breeding",
      status: "completed",
      principal: "001",
      offers: [{ id: "004" }, { id: "006" }],
      proxzi: "004",
      paymentId: "011",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
      completedAt: "2023-02-27T03:57:50.232+00:00",
    },
    {
      id: "18",
      bill: "34720812.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-07",
      isCertified: true,
      lga: "Amuwo-Odofin",
      occupation: "Lawyers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Buy business",
      status: "completed",
      principal: "001",
      offers: [{ id: "002" }, { id: "006" }],
      proxzi: "006",
      paymentId: "012",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
      completedAt: "2023-02-27T03:57:50.232+00:00",
    },
    {
      id: "19",
      bill: "48009024.00",
      eduLevel: "OND",
      endDate: "2023-03-23",
      isCertified: false,
      lga: "Ojokoro",
      occupation: "Statisticians",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-15",
      state: "Lagos",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Plus and minus",
      status: "confirmed",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      proxzi: "004",
      paymentId: "013",
      proxziPaymentId: "005",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
      confirmedAt: "2023-03-02T04:32:50.232+00:00",
      completedAt: "2023-03-01T03:57:50.232+00:00",
    },
    {
      id: "20",
      bill: "92588832.00",
      eduLevel: "HND/BSc",
      endDate: "2023-03-17",
      isCertified: false,
      lga: "Lagos Mainland",
      occupation: "Medical doctors",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-08",
      state: "Lagos",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Cut wrists",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      status: "confirmed",
      principal: "001",
      offers: [{ id: "002" }, { id: "004" }, { id: "006" }],
      proxzi: "002",
      paymentId: "014",
      proxziPaymentId: "004",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
      confirmedAt: "2023-02-28T04:32:50.232+00:00",
      completedAt: "2023-02-27T03:57:50.232+00:00",
    },
    {
      id: "21",
      bill: "925888320.00",
      eduLevel: "PhD",
      endDate: "2023-03-24",
      isCertified: true,
      lga: "Apapa",
      occupation: "Biologists, zoologists and related scientists",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-06",
      state: "Lagos",
      timeBlock: "Night",
      yearsOfExp: "10 years & above",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Fish population",
      status: "confirmed",
      principal: "003",
      offers: [{ id: "002" }, { id: "004" }],
      proxzi: "004",
      paymentId: "015",
      proxziPaymentId: "003",
      createdAt: "2023-02-17T08:45:40.232+00:00",
      approvedAt: "2023-02-18T08:50:40.232+00:00",
      assignedAt: "2023-02-18T09:50:40.232+00:00",
      startedAt: "2023-02-19T02:50:40.232+00:00",
      confirmedAt: "2023-02-28T04:32:50.232+00:00",
      completedAt: "2023-02-22T03:57:50.232+00:00",
    },
    {
      id: "22",
      bill: "34720812.00",
      eduLevel: "MSc/MBA",
      endDate: "2023-03-07",
      isCertified: true,
      lga: "Amuwo-Odofin",
      occupation: "Lawyers",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-05",
      state: "Lagos",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "I don't want to go to jail",
      status: "confirmed",
      principal: "001",
      offers: [{ id: "002" }, { id: "006" }],
      proxzi: "006",
      paymentId: "016",
      proxziPaymentId: "002",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T02:50:40.232+00:00",
      confirmedAt: "2023-02-28T04:32:50.232+00:00",
      completedAt: "2023-02-26T03:57:50.232+00:00",
    },
    {
      id: "23",
      bill: "48009024.00",
      eduLevel: "OND",
      endDate: "2023-03-23",
      isCertified: false,
      lga: "Ojokoro",
      occupation: "Statisticians",
      searchRange: "LGA",
      skillLevel: "Skilled",
      startDate: "2023-03-15",
      state: "Lagos",
      timeBlock: "Day",
      yearsOfExp: "4-6 years",
      taskDesc:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos! Nihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!\n\nNihil illum quae est autem illo dolores, ipsa, non iusto voluptatem eveniet consequuntur blanditiis dolor provident eum praesentium nobis enim, veniam quos!",
      taskName: "Minus and plus",
      status: "confirmed",
      principal: "001",
      offers: [{ id: "004" }, { id: "006" }],
      proxzi: "004",
      paymentId: "017",
      proxziPaymentId: "001",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      approvedAt: "2023-02-25T08:50:40.232+00:00",
      assignedAt: "2023-02-25T09:50:40.232+00:00",
      startedAt: "2023-02-26T04:50:40.232+00:00",
      completedAt: "2023-02-27T03:57:50.232+00:00",
      confirmedAt: "2023-02-28T04:32:50.232+00:00",
    },
  ],
  users: [
    {
      id: "001",
      userType: "Principal",
      firstName: "One",
      lastName: "Principal",
      email: "one.principal@test.com",
      password: "Password123",
      address: "1234 Main St.",
    },
    {
      id: "002",
      userType: "Proxzi",
      firstName: "Two",
      lastName: "Proxzi",
      email: "two.proxzi@test.com",
      password: "Password123",
      address: "1234 Main St.",
      occupation: "Medical doctors",
    },
    {
      id: "003",
      userType: "Principal",
      firstName: "Three",
      lastName: "Principal",
      email: "three.principal@test.com",
      password: "Password123",
      address: "1234 Main St.",
    },
    {
      id: "004",
      userType: "Proxzi",
      firstName: "Four",
      lastName: "Proxzi",
      email: "four.proxzi@test.com",
      password: "Password123",
      address: "1234 Main St.",
      occupation: "Architects and town planners",
    },
    {
      id: "005",
      userType: "Principal",
      firstName: "Five",
      lastName: "Principal",
      email: "five.principal@test.com",
      password: "Password123",
      address: "1234 Main St.",
    },
    {
      id: "006",
      userType: "Proxzi",
      firstName: "Six",
      lastName: "Proxzi",
      email: "six.proxzi@test.com",
      password: "Password123",
      address: "1234 Main St.",
      occupation: "Biologists, zoologists and related scientists",
    },
  ],
  notifications: [
    {
      type: "approve",
      taskId: "4",
      isOpened: false,
      isSeen: true,
      createdAt: "2023-02-27T08:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "8",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      type: "approve",
      taskId: "5",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T09:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "6",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T07:45:40.232+00:00",
    },
    {
      type: "approve",
      taskId: "7",
      isOpened: false,
      isSeen: true,
      createdAt: "2023-02-26T10:45:40.232+00:00",
    },
    {
      type: "offer",
      taskId: "7",
      isOpened: false,
      isSeen: false,
      createdAt: "2023-03-08T08:45:40.232+00:00",
    },
    {
      type: "offer",
      taskId: "9",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-03-01T08:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "9",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T11:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "2",
      isOpened: false,
      isSeen: false,
      createdAt: "2023-03-07T08:45:40.232+00:00",
    },
    {
      type: "credit",
      amount: 76000,
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-27T08:45:40.232+00:00",
    },
    {
      type: "offer",
      taskId: "11",
      isOpened: false,
      isSeen: false,
      createdAt: "2023-03-09T10:45:40.232+00:00",
    },
    {
      type: "complete",
      taskId: "15",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-24T08:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "10",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      type: "complete",
      taskId: "17",
      isOpened: false,
      isSeen: true,
      createdAt: "2023-02-28T08:45:40.232+00:00",
    },
    {
      type: "debit",
      amount: 5000,
      isOpened: false,
      isSeen: true,
      createdAt: "2023-02-28T08:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "1",
      isOpened: false,
      isSeen: true,
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      type: "review",
      reviewId: "4",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      type: "complete",
      taskId: "21",
      isOpened: false,
      isSeen: false,
      createdAt: "2023-03-09T03:45:40.232+00:00",
    },
    {
      type: "credit",
      amount: 56000,
      isOpened: false,
      isSeen: false,
      createdAt: "2023-03-09T03:45:40.232+00:00",
    },
    {
      type: "complete",
      taskId: "20",
      isOpened: true,
      isSeen: true,
      createdAt: "2023-02-25T08:45:40.232+00:00",
    },
    {
      type: "complete",
      taskId: "19",
      isOpened: false,
      isSeen: false,
      createdAt: "2023-03-08T08:45:40.232+00:00",
    },
  ],
  transactions: [
    {
      id: "002",
      type: "credit",
      purpose: "payment",
      amount: "263299491.00",
      createdAt: "2023-03-03T08:45:40.232+00:00",
      taskId: "5",
    },
    {
      id: "001",
      type: "credit",
      purpose: "funding",
      amount: "263299491.00",
      createdAt: "2023-02-25T08:45:40.232+00:00",
      taskId: "5",
    },
    {
      id: "003",
      type: "debit",
      purpose: "withdrawal",
      amount: "66599491.00",
      createdAt: "2023-03-12T08:45:40.232+00:00",
    },
    {
      id: "004",
      type: "credit",
      purpose: "funding",
      amount: "463299491.00",
      createdAt: "2023-02-26T08:45:40.232+00:00",
      taskId: "6",
    },
    {
      id: "005",
      type: "debit",
      purpose: "withdrawal",
      amount: "3299491.00",
      createdAt: "2023-03-01T08:45:40.232+00:00",
    },
    {
      id: "006",
      type: "credit",
      purpose: "payment",
      amount: "463299491.00",
      createdAt: "2023-03-05T08:45:40.232+00:00",
      taskId: "6",
    },
  ],
};

export default testData;
