// const locationClass = { high: 2, mid: 1.5, low: 1 };

const settings = {
  states: [
    {
      locationState: "Lagos",
      lgas: [
        { location: "Agege", multiple: "Low" },
        { location: "Orile-Agege", multiple: "Low" },
        { location: "Ajeromi", multiple: "Low" },
        { location: "Ifelodun", multiple: "Low" },
        { location: "Alimosho", multiple: "Mid" },
        { location: "Agbado/Oke-Odo", multiple: "High" },
        { location: "Ayobo-Ipaja", multiple: "Mid" },
        { location: "Egbe-Idimu", multiple: "Mid" },
        { location: "Igando-Ikotun", multiple: "Low" },
        { location: "Mosan Okunola", multiple: "Low" },
        { location: "Amuwo Odofin", multiple: "Mid" },
        { location: "Oriade", multiple: "Low" },
        { location: "Apapa", multiple: "High" },
        { location: "AgeApapa Iganmu", multiple: "Low" },
        { location: "Badagry", multiple: "Low" },
        { location: "Badagry West", multiple: "Low" },
        { location: "Olorunda", multiple: "Low" },
        { location: "Epe", multiple: "Mid" },
        { location: "Eredo", multiple: "Low" },
        { location: "Ikosi Ejinrin", multiple: "Mid" },
        { location: "Eti Osa", multiple: "High" },
        { location: "Iru Victoria Island", multiple: "High" },
        { location: "Ikoyi-Obalende", multiple: "High" },
        { location: "Ibeju", multiple: "High" },
        { location: "Lekki", multiple: "High" },
        { location: "Ifako/Ijaiye", multiple: "Mid" },
        { location: "Ojokoro", multiple: "Low" },
        { location: "Ikeja", multiple: "High" },
        { location: "Ojodu", multiple: "Mid" },
        { location: "Onigbongbo", multiple: "Low" },
        { location: "Ikorodu", multiple: "Low" },
        { location: "Ikorodu North", multiple: "Low" },
        { location: "Ikorodu West", multiple: "Low" },
        { location: "Imota", multiple: "Low" },
        { location: "Ijede", multiple: "Low" },
        { location: "Igbogbo-Baiyeku", multiple: "Low" },
        { location: "Kosofe", multiple: "Mid" },
        { location: "Ikosi Isheri", multiple: "Mid" },
        { location: "Agboyi-Ketu", multiple: "Low" },
        { location: "Lagos Island", multiple: "High" },
        { location: "Lagos Mainland", multiple: "Mid" },
        { location: "Yaba", multiple: "Mid" },
        { location: "Mushin", multiple: "Low" },
        { location: "Odi-Olowo", multiple: "Low" },
        { location: "Ojo", multiple: "Low" },
        { location: "Oto Awori", multiple: "Low" },
        { location: "Iba", multiple: "Low" },
        { location: "Shomolu", multiple: "Mid" },
        { location: "Bariga", multiple: "Low" },
        { location: "Ejigbo", multiple: "Low" },
        { location: "Isolo", multiple: "Low" },
        { location: "Oshodi", multiple: "Low" },
        { location: "Surulere", multiple: "High" },
        { location: "Coker Aguda", multiple: "Low" },
        { location: "Itire-Ikate", multiple: "Low" },
      ],
    },
    {
      locationState: "Abuja",
      lgas: [
        { location: "Abaji", multiple: "Low" },
        { location: "Bwari", multiple: "Low" },
        { location: "Gwagwalada", multiple: "Low" },
        { location: "Kuje", multiple: "Low" },
        { location: "Kwali", multiple: "Mid" },
        { location: "Municipal Area Council", multiple: "High" },
      ],
    },
    {
      locationState: "Port Harcourt",
      lgas: [
        { location: "Abua/Odual", multiple: "Low" },
        { location: "Ahoada East", multiple: "Low" },
        { location: "Ahoada West", multiple: "Low" },
        { location: "Akuku-Toru", multiple: "Low" },
        { location: "Andoni", multiple: "Mid" },
        { location: "Asari-Toru", multiple: "High" },
        { location: "Bonny", multiple: "Mid" },
        { location: "Degema", multiple: "Mid" },
        { location: "Eleme", multiple: "Low" },
        { location: "Emuoha", multiple: "Low" },
        { location: "Etche", multiple: "Mid" },
        { location: "Gokana", multiple: "Low" },
        { location: "Ikwerre", multiple: "High" },
        { location: "Khana", multiple: "Low" },
        { location: "Obio/Akpor", multiple: "Low" },
        { location: "Ogba/Egbema/Ndoni", multiple: "Low" },
        { location: "Ogu/Bolo", multiple: "Low" },
        { location: "Okrika", multiple: "Mid" },
        { location: "Omuma", multiple: "Low" },
        { location: "Opobo/Nkoro", multiple: "Mid" },
        { location: "Oyigbo", multiple: "High" },
        { location: "Port Harcourt", multiple: "High" },
        { location: "Tai", multiple: "High" },
      ],
    },
    {
      locationState: "Enugu",
      lgas: [
        { location: "Aninri", multiple: "Low" },
        { location: "Awgu", multiple: "Low" },
        { location: "Enugu East", multiple: "Low" },
        { location: "Enugu North", multiple: "Low" },
        { location: "Enugu South", multiple: "Mid" },
        { location: "Ezeagu", multiple: "High" },
        { location: "Igbo Etiti", multiple: "Mid" },
        { location: "Igbo Eze North", multiple: "Mid" },
        { location: "Igbo Eze South", multiple: "Low" },
        { location: "Isi Uzo", multiple: "Low" },
        { location: "Nkanu East", multiple: "Mid" },
        { location: "Nkanu West", multiple: "Low" },
        { location: "Nsukka", multiple: "High" },
        { location: "Oji River", multiple: "Low" },
        { location: "Udenu", multiple: "Low" },
        { location: "Udi", multiple: "Low" },
        { location: "Uzo Uwani", multiple: "Low" },
      ],
    },
    {
      locationState: "Cross River",
      lgas: [
        { location: "Abi", multiple: "Low" },
        { location: "Akamkpa", multiple: "Low" },
        { location: "Akpabuyo", multiple: "Low" },
        { location: "Bakassi", multiple: "Low" },
        { location: "Bekwarra", multiple: "Mid" },
        { location: "Biase", multiple: "High" },
        { location: "Boki", multiple: "Mid" },
        { location: "Calabar Municipal", multiple: "Mid" },
        { location: "Calabar South", multiple: "Low" },
        { location: "Etung", multiple: "Low" },
        { location: "Ikom", multiple: "Mid" },
        { location: "Obanliku", multiple: "Low" },
        { location: "Obubra", multiple: "High" },
        { location: "Obudu", multiple: "Low" },
        { location: "Odukpani", multiple: "Low" },
        { location: "Ogoja", multiple: "Low" },
        { location: "Yakuur", multiple: "Low" },
        { location: "Yala", multiple: "Mid" },
      ],
    },
    {
      locationState: "Kano",
      lgas: [
        { location: "Ajingi", multiple: "Low" },
        { location: "Albasu", multiple: "Low" },
        { location: "Bagwai", multiple: "Low" },
        { location: "Bebeji", multiple: "Low" },
        { location: "Bichi", multiple: "Mid" },
        { location: "Bunkure", multiple: "High" },
        { location: "Dala", multiple: "Mid" },
        { location: "Dambatta", multiple: "Mid" },
        { location: "Dawakin Kudu", multiple: "Low" },
        { location: "Dawakin Tofa", multiple: "Low" },
        { location: "Doguwa", multiple: "Mid" },
        { location: "Fagge", multiple: "Low" },
        { location: "Gabasawa", multiple: "High" },
        { location: "Garko", multiple: "Low" },
        { location: "Garun Mallam", multiple: "Low" },
        { location: "Gaya", multiple: "Low" },
        { location: "Gezawa", multiple: "Low" },
        { location: "Gwale", multiple: "Mid" },
        { location: "Gwarzo", multiple: "Low" },
        { location: "Kabo", multiple: "Mid" },
        { location: "Kano Municipal", multiple: "High" },
        { location: "Karaye", multiple: "High" },
        { location: "Kibiya", multiple: "High" },
        { location: "Kiru", multiple: "High" },
        { location: "Kumbotso", multiple: "High" },
        { location: "Kunchi", multiple: "High" },
        { location: "Kura", multiple: "Mid" },
        { location: "Madobi", multiple: "Low" },
        { location: "Makoda", multiple: "High" },
        { location: "Minjibir", multiple: "Mid" },
        { location: "Nasarawa", multiple: "Low" },
        { location: "Rano", multiple: "Low" },
        { location: "Rimin Gado", multiple: "Low" },
        { location: "Rogo", multiple: "Low" },
        { location: "Shanono", multiple: "Low" },
        { location: "Sumaila", multiple: "Low" },
        { location: "Takai", multiple: "Low" },
        { location: "Tarauni", multiple: "Mid" },
        { location: "Tofa", multiple: "Mid" },
        { location: "Tsanyawa", multiple: "Low" },
        { location: "Tudun Wada", multiple: "High" },
        { location: "Ungogo", multiple: "High" },
        { location: "Warawa", multiple: "Mid" },
        { location: "Wudil", multiple: "Mid" },
      ],
    },
  ],

  types: [
    { type: "Verification", value: 1 },
    { type: "Consultation", value: 1 },
    { type: "Errand", value: 1 },
  ],

  educationLevel: [
    { level: "FSCL", value: 1 },
    { level: "SSCE", value: 1.2 },
    { level: "OND", value: 1.4 },
    { level: "HND/BSc", value: 1.6 },
    { level: "MSc/MBA", value: 1.8 },
    { level: "PhD", value: 2 },
  ],

  certification: [
    { type: "Yes", value: 1.5 },
    { type: "No", value: 1 },
  ],

  yearsOfExp: [
    { range: "1-3 years", value: 1 },
    { range: "4-6 years", value: 1.2 },
    { range: "7-9 years", value: 1.4 },
    { range: "10 years & above", value: 1.6 },
  ],

  skillLevel: [
    { level: "Skilled", value: 1.5 },
    { level: "Unskilled", value: 1 },
  ],

  searchRange: [
    { range: "5 Kilometers", value: 1 },
    { range: "25 Kilometers", value: 1.2 },
    { range: "50 Kilometers", value: 1.4 },
    { range: "100 Kilometers", value: 1.6 },
    { range: "Wards", value: 1.8 },
    { range: "LGA", value: 2 },
    { range: "State", value: 2.2 },
    { range: "Country", value: 2.4 },
  ],

  dateBlock: [
    { type: "Range (6am - 6pm daily)", value: 1 },
    { type: "Specify", value: 1.2 },
  ],

  timeBlock: [
    { type: "Range (6am - 6pm daily)", value: 1 },
    { type: "Specify", value: 1.2 },
  ],

  durationMultiples: [
    { type: "Multiple 1", value: 1 },
    { type: "Multiple 2", value: 2 },
    { type: "Multiple 2", value: 3 },
    { type: "Multiple 4", value: 4 },
  ],

  occupations: [
    { occupation: "Chemists" },
    { occupation: "Physicists" },
    { occupation: "Physical scientists not elsewhere classified" },
    { occupation: "Physical science technicians" },
    { occupation: "Architects and town planners" },
    { occupation: "Civil engineers" },
    { occupation: "Electrical and electronics engineers" },
    { occupation: "Mechanical engineers" },
    { occupation: "Chemical engineers" },
    { occupation: "Metallurgists" },
    { occupation: "Mining engineers" },
    { occupation: "Industrial engineers" },
    { occupation: "Engineers not elsewhere classified" },
    { occupation: "Surveyors" },
    { occupation: "Draughtsmen" },
    { occupation: "Civil engineering technicians" },
    { occupation: "Electrical and electronics engineering technicians" },
    { occupation: "Mechanical engineering technicians" },
    { occupation: "Chemical engineering technicians" },
    { occupation: "Metallurgical technicians" },
    { occupation: "Mining technicians" },
    { occupation: "Engineering technicians not elsewhere classified" },
    { occupation: "Aircraft pilots, navigators and flight engineers" },
    { occupation: "Ships' deck officers and pilots" },
    { occupation: "Ships' engineers" },
    { occupation: "Biologists, zoologists and related scientists" },
    { occupation: "Bacteriologists, pharmacologists and related scientists" },
    { occupation: "Agronomists and related scientists" },
    { occupation: "Life sciences technicians" },
    { occupation: "Medical doctors" },
    { occupation: "Medical assistants" },
    { occupation: "Dentists" },
    { occupation: "Dental assistants" },
    { occupation: "Veterinarians" },
    { occupation: "Veterinary assistants" },
    { occupation: "Pharmacists" },
    { occupation: "Pharmaceutical assistants" },
    { occupation: "Dietitians and public health nutritionists" },
    { occupation: "Professional nurses" },
    { occupation: "Nursing personnel not elsewhere classified" },
    { occupation: "Professional midwives" },
    { occupation: "Midwifery personnel not elsewhere classified" },
    { occupation: "Optometrists and opticians" },
    { occupation: "Physiotherapists and occupational therapists" },
    { occupation: "Medical X-ray technicians" },
    {
      occupation:
        "Medical, dental, veterinary and related workers not elsewhere classified",
    },
    { occupation: "Statisticians" },
    { occupation: "Mathematicians and actuaries" },
    { occupation: "Systems Analysts" },
    { occupation: "Statistical and mathematical technicians" },
    { occupation: "Economists" },
    { occupation: "Accountants" },
    { occupation: "Lawyers" },
    { occupation: "Judges" },
    { occupation: "Jurists not elsewhere classified" },
    { occupation: "University and higher education teachers" },
    { occupation: "Secondary education teachers" },
    { occupation: "Primary education teachers" },
    { occupation: "Pre-primary education teachers" },
    { occupation: "Special education teachers" },
    { occupation: "Teachers not elsewhere classified" },
    {
      occupation:
        "Ministers of religion and related members of religious orders",
    },
    { occupation: "Workers in religion not elsewhere classified" },
    { occupation: "Authors and critics" },
    {
      occupation:
        "Authors, journalists and related writers not elsewhere classified",
    },
    { occupation: "Sculptors, painters and related artists" },
    { occupation: "Commercial artists and designers" },
    { occupation: "Photographers and cameramen" },
    { occupation: "Composers, musicians and singers" },
    { occupation: "Choreographers and dancers" },
    { occupation: "Actors and stage directors" },
    { occupation: "Producers, performing arts" },
    { occupation: "Circus performers" },
    { occupation: "Performing artists not elsewhere classified" },
    { occupation: "Athletes, sportsmen and related workers" },
    { occupation: "Librarians, archivists and curators" },
    { occupation: "Sociologists, anthropologists and related scientists" },
    { occupation: "Social workers" },
    { occupation: "Personnel and occupational specialists" },
    { occupation: "Philologists, translators and interpreters" },
    { occupation: "Other professional, technical and related workers" },
    { occupation: "Legislative officials" },
    { occupation: "Government administrators" },
    { occupation: "General managers" },
    { occupation: "Production managers (except farm)" },
    { occupation: "Managers not elsewhere classified" },
    { occupation: "Clerical supervisors" },
    { occupation: "Government executive officials" },
    { occupation: "Stenographers, typists and teletypists" },
    { occupation: "Card- and tape-punching machine operators" },
    { occupation: "Bookkeepers and cashiers" },
    {
      occupation:
        "Bookkeepers, cashiers and related workers not elsewhere classified",
    },
    { occupation: "Bookkeeping and calculating machine operators" },
    { occupation: "Automatic data-processing machine operators" },
    { occupation: "Railway station masters" },
    { occupation: "Postmasters" },
    {
      occupation:
        "Transport and communications supervisors not elsewhere classified",
    },
    { occupation: "Transport conductors" },
    { occupation: "Mail distribution clerks" },
    { occupation: "Telephone and telegraph operators" },
    { occupation: "Stock clerks" },
    { occupation: "Material and production planning clerks" },
    { occupation: "Correspondence and reporting clerks" },
    { occupation: "Receptionists and travel agency clerks" },
    { occupation: "Library and filing clerks" },
    { occupation: "Clerks not elsewhere classified" },
    { occupation: "Managers (wholesale and retail trade)" },
    { occupation: "Working proprietors (wholesale and retail trade)" },
    { occupation: "Sales supervisors" },
    { occupation: "Buyers" },
    { occupation: "Technical salesmen and service advisers" },
    { occupation: "Commercial travellers and Manufacturers' agents" },
    { occupation: "Insurance, real estate and securities salesmen" },
    { occupation: "Business services salesmen" },
    { occupation: "Auctioneers" },
    { occupation: "Salesmen, shop assistants and demonstrators" },
    { occupation: "Street vendors, canvassers and newsvendors" },
    { occupation: "Sales workers not elsewhere classified" },
    { occupation: "Managers (catering and lodging services)" },
    { occupation: "Working proprietors (catering and lodging services)" },
    { occupation: "Housekeeping and related service supervisors" },
    { occupation: "Cooks" },
    { occupation: "Waiters, bartenders and related workers" },
    {
      occupation:
        "Maids and related housekeeping service workers not elsewhere classified",
    },
    { occupation: "Building caretakers" },
    { occupation: "Charworkers, cleaners and related workers" },
    { occupation: "Launderers, dry-cleaners and pressers" },
    { occupation: "Hairdressers, barbers, beauticians and related workers" },
    { occupation: "Fire-fighters" },
    { occupation: "Policemen and detectives" },
    { occupation: "Protective service workers not elsewhere classified" },
    { occupation: "Guides" },
    { occupation: "Undertakers and embalmers" },
    { occupation: "Other service workers" },
    { occupation: "Farm managers and supervisors" },
    { occupation: "General farmers" },
    { occupation: "Specialised farmers" },
    { occupation: "General farm workers" },
    { occupation: "Field crop and vegetable farm workers" },
    { occupation: "Orchard, vineyard and related tree and shrub crop workers" },
    { occupation: "Livestock workers" },
    { occupation: "Dairy farm workers" },
    { occupation: "Poultry farm workers" },
    { occupation: "Nursery workers and gardeners" },
    { occupation: "Farm machinery operators" },
    {
      occupation:
        "Agricultural and animal husbandry workers not elsewhere classified",
    },
    { occupation: "Loggers" },
    { occupation: "Forestry workers (except logging)" },
    { occupation: "Fishermen" },
    {
      occupation:
        "Fishermen, hunters and related workers not elsewhere classified",
    },
    { occupation: "Production supervisors and general foremen" },
    { occupation: "Miners and quarrymen" },
    { occupation: "Mineral and stone treaters" },
    { occupation: "Well drillers, borers and related workers" },
    { occupation: "Metal smelting, converting and refining furnacemen" },
    { occupation: "Metal rolling-mill workers" },
    { occupation: "Metal melters and reheaters" },
    { occupation: "Metal casters" },
    { occupation: "Metal moulders and coremakers" },
    { occupation: "Metal annealers, temperers and case-hardeners" },
    { occupation: "Metal drawers and extruders" },
    { occupation: "Metal platers and coaters" },
    { occupation: "Metal processers not elsewhere classified" },
    { occupation: "Wood treaters" },
    {
      occupation: "Sawyers, plywood makers and related wood-processing workers",
    },
    { occupation: "Paper pulp preparers" },
    { occupation: "Paper makers" },
    { occupation: "Crushers, grinders and mixers" },
    { occupation: "Cookers, roasters and related heat-treaters" },
    { occupation: "Filter and separator operators" },
    { occupation: "Still and reactor operators" },
    { occupation: "Petroleum-refining workers" },
    {
      occupation:
        "Chemical processers and related workers not elsewhere classified",
    },
    { occupation: "Fibre preparers" },
    { occupation: "Spinners and winders" },
    {
      occupation:
        "Weaving- and knitting-machine setters and pattern-card preparers",
    },
    { occupation: "Weavers and related workers" },
    { occupation: "Knitters" },
    { occupation: "Bleachers, dyers and textile product finishers" },
    {
      occupation:
        "Spinners, weavers, knitters, dyers and related workers not elsewhere classified",
    },
    { occupation: "Tanners and fellmongers" },
    { occupation: "Pelt dressers" },
    { occupation: "Grain millers and related workers" },
    { occupation: "Sugar processers and refiners" },
    { occupation: "Butchers and meat preparers" },
    { occupation: "Food preservers" },
    { occupation: "Dairy product processers" },
    { occupation: "Bakers, pastrycooks and confectionery makers" },
    { occupation: "Tea, coffee and cocoa preparers" },
    { occupation: "Brewers, wine and beverage makers" },
    { occupation: "Food and beverage processers not elsewhere classified" },
    { occupation: "Tailors and dressmakers" },
    { occupation: "Fur tailors and related workers" },
    { occupation: "Milliners and hatmakers" },
    { occupation: "Patternmakers and cutters" },
    { occupation: "Sewers and embroiderers" },
    { occupation: "Upholsterers and related workers" },
    {
      occupation:
        "Tailors, dressmakers, sewers, upholsterers and related workers not elsewhere classified",
    },
    { occupation: "Shoemakers and shoe repairers" },
    { occupation: "Shoe cutters, lasters, sewers and related workers" },
    { occupation: "Leather goods makers" },
    { occupation: "Cabinetmakers" },
    { occupation: "Woodworking-machine operators" },
    {
      occupation:
        "Cabinetmakers and related woodworkers not elsewhere classified ",
    },
    { occupation: "Stone cutters and carvers" },
    { occupation: "Blacksmiths, hammersmiths and forging-press operators" },
    { occupation: "Toolmakers, metal patternmakers and metal markers" },
    { occupation: "Machine-tool setter-operators" },
    { occupation: "Machine-tool operators" },
    { occupation: "Metal grinders, polishers and tool sharpeners" },
    {
      occupation:
        "Blacksmiths, toolmakers and machine-tool operators not elsewhere classified ",
    },
    { occupation: "Machinery fitters and machine assemblers" },
    { occupation: "Watch, clock and precision instrument makers" },
    { occupation: "Motor vehicle mechanics" },
    { occupation: "Aircraft engine mechanics" },
    {
      occupation:
        "Machinery fitters, machine assemblers and precision instrument makers (except electrical) not elsewhere classified ",
    },
    { occupation: "Electrical fitters" },
    { occupation: "Electronics fitters" },
    { occupation: "Electrical and electronics equipment assemblers" },
    { occupation: "Radio and television repairmen" },
    { occupation: "Electrical wiremen" },
    { occupation: "Telephone and telegraph installers" },
    { occupation: "Electric linemen and cable jointers" },
    {
      occupation:
        "Electrical fitters and related electrical and electronics workers not elsewhere classified",
    },
    { occupation: "Broadcasting station operators" },
    { occupation: "Sound equipment operators and cinema projectionists" },
    { occupation: "Plumbers and pipe fitters" },
    { occupation: "Welders and flame-cutters" },
    { occupation: "Sheet-metal workers" },
    { occupation: "Structural metal preparers and erectors" },
    { occupation: "Jewellery and precious metal workers" },
    { occupation: "Glass formers, cutters, grinders and finishers" },
    { occupation: "Potters and related clay and abrasive formers" },
    { occupation: "Glass and ceramics kilnmen" },
    { occupation: "Glass engravers and etchers" },
    { occupation: "Glass and ceramics painters and decorators" },
    {
      occupation:
        "Glass formers, potters and related workers not elsewhere classified",
    },
    {
      occupation:
        "Rubber and plastics product makers (except tire makers and tire vulcanisers)",
    },
    { occupation: "Tire makers and vulcanisers" },
    { occupation: "Paper and paperboard products makers" },
    { occupation: "Compositors and typesetters" },
    { occupation: "Printing pressmen" },
    { occupation: "Stereotypers and electrotypers" },
    { occupation: "Printing engravers (except photo-engravers)" },
    { occupation: "Photo-engravers" },
    { occupation: "Bookbinders and related workers" },
    { occupation: "Photographic darkroom workers" },
    { occupation: "Printers and related workers not elsewhere classified" },
    { occupation: "Painters, construction" },
    { occupation: "Painters not elsewhere classified" },
    { occupation: "Musical instrument makers and tuners" },
    { occupation: "Basketry weavers and brush makers" },
    { occupation: "Non-metallic mineral product makers" },
    { occupation: "Other production and related workers" },
    { occupation: "Bricklayers, stonemasons and tile setters" },
    {
      occupation:
        "Reinforced-concreters, cement finishers and terrazzo workers",
    },
    { occupation: "Roofers" },
    { occupation: "Carpenters, joiners and parquetry workers" },
    { occupation: "Plasterers" },
    { occupation: "Insulators" },
    { occupation: "Glaziers" },
    { occupation: "Construction workers not elsewhere classified" },
    { occupation: "Power-generating machinery operators" },
    {
      occupation:
        "Stationary engine and related equipment operators not elsewhere classified",
    },
    { occupation: "Dockers and freight handlers" },
    { occupation: "Riggers and cable splicers" },
    { occupation: "Crane and hoist operators" },
    { occupation: "Earth-moving and related machinery operators" },
    {
      occupation:
        "Material-handling equipment operators not elsewhere classified",
    },
    { occupation: "Ships' deck ratings, barge crews and boatmen" },
    { occupation: "Ships' engine-room ratings" },
    { occupation: "Railway engine drivers and firemen" },
    { occupation: "Railway brakemen, signalmen and shunters" },
    { occupation: "Motor vehicle drivers" },
    { occupation: "Animal and animal-drawn vehicle drivers" },
    { occupation: "Transport equipment operators not elsewhere classified" },
    { occupation: "Labourers not elsewhere classified" },
    { occupation: "Graphics Design" },
    { occupation: "UX Design" },
    { occupation: "Architecture and Interior Design" },
    { occupation: "Writing and Translation" },
    { occupation: "Video and Animation" },
    { occupation: "Music and Audio" },
    { occupation: "Programming and Tech" },
    { occupation: "Data modelling and Data Science" },
  ],
};

export default settings;
